spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_demo
    username: root
    password: sb@12345
  jpa:
    hibernate:
      #dialect: org.hibernate.dialect.MySQL5InnoDbDialec
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
      name: SpringBoot - USER_SERVICE


